cls: PasstFiLMConditionedBandit
kwargs:
  in_channel: 2
  band_type: "musical"
  n_bands: 64
  additive_film: true
  multiplicative_film: true
  film_depth: 2
  n_sqm_modules: 8
  emb_dim: 128
  rnn_dim: 256
  bidirectional: true
  rnn_type: "GRU"
  mlp_dim: 512
  hidden_activation: "Tanh"
  hidden_activation_kwargs: null
  complex_mask: true
  use_freq_weights: true
  n_fft: 2048
  win_length: 2048
  hop_length: 512
  window_fn: "hann_window"
  wkwargs: null
  power: null
  center: true
  normalized: true
  pad_mode: "reflect"
  onesided: true
  fs: 44100
  pretrain_encoder: /storage/home/hcoda1/1/kwatchar3/data/logs/e2e/lightning_logs/bandit-vdbo-gru-aug/checkpoints/epoch=99-step=204800.ckpt
  freeze_encoder: true