callbacks:
  checkpoint:
    monitor: val/loss
    mode: min
    save_top_k: 3
    save_last: True
max_epochs: 150
accumulate_grad_batches: null
gradient_clip_val: 10.0
gradient_clip_algorithm: norm
logger:
  save_dir: ${oc.env:LOG_ROOT}/e2e